### ISSUE TITLE
 API giving 400 request with Go REST API client

### ISSUE THREAD

**Issue by siddheshwar-more** [semaphoreci/api#26]
```
package main

import (
	"fmt"
	"net/http"
	"io/ioutil"
)

func main() {

	url := "https://instantlabs.semaphoreci.com/api/v1alpha/plumber-workflows?project_id=8ba6c38a-3c71-42b3-80bc-0d2d3571bacd"

	req, _ := http.NewRequest("GET", url, nil)

	req.Header.Add("authorization", "Token **xxxxxxxxxxxxxxx**")
	req.Header.Add("content-type", "application/x-www-form-urlencoded")

	res, _ := http.DefaultClient.Do(req)

	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)

	fmt.Println(res)
	fmt.Println(string(body))

}
```

**OUTPUT:**
&{400 Bad Request 400 HTTP/2.0 2 0 map[Via:[1.1 google] Alt-Svc:[clear] Cache-Control:[max-age=0, private, must-revalidate] Content-Length:[170] Date:[Tue, 08 Sep 2020 17:25:41 GMT] Server:[envoy] X-Envoy-Upstream-Service-Time:[1]] {0xc000102500} 170 [] false false map[] 0xc0000d4000 0xc00014a160}
{"message": "Call rejected because the client is outdated. To continue, upgrade Semaphore CLI with 'curl https://storage.googleapis.com/sem-cli-releases/get.sh | bash'."}

**Comment by siddheshwar-more** [comment]
@radwo  below python code is working - not sure why its not working for GO lang

```
import http.client

conn = http.client.HTTPSConnection("instantlabs.semaphoreci.com")

payload = ""

headers = {
    'authorization': "Token xxxxxxxxxxxxx",
    'content-type': "application/x-www-form-urlencoded"
    }

conn.request("GET", "/api/v1alpha/plumber-workflows?project_id=8ba6c38a-3c71-42b3-80bc-0d2d3571bacd", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
```

**Comment by radwo** [comment]
Hi Siddheshwar, thanks for using Semaphore.

Please set a custom user_agent header in the GO client, and this will resolve the issue.
This message is part of our system that prevents using outdated CLI client, which we write in GO.

**Comment by siddheshwar-more** [comment]
@radwo Thanks its working with custom header `User-Agent = iL-Agent 1.0` . 
Let me know if you suggest any other standard value as per the api implementation.
